name: Retrain Model

on:
  push:
    paths:
      - "housing.csv"
      - "train.py"

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install scikit-learn mlflow pandas
      - name: Train Model
        run: python train.py

