name: Retrain Model

on:
  push:
    paths:
      - "housing.csv"
      - "train.py"

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repo
      - uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn mlflow pandas

      # Step 4: Remove old MLflow runs to avoid path issues
      - name: Clean MLflow runs
        run: rm -rf mlruns

      # Step 5: Train model
      - name: Train Model
        run: python train.py

      # Step 6: Upload MLflow artifacts (optional)
      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-runs
          path: mlruns/
